[build]
  command = "npx @11ty/eleventy"
  publish = "_site"
[build.environment]
NODE_VERSION = "22"
[context.production.environment]
  ELEVENTY_ENV = "production"

[context."branch:staging".environment]
  ELEVENTY_ENV = "preview"

[context."branch:staging".headers]
  for = "/*"
  [context."branch:staging".headers.values]
    X-Robots-Tag = "noindex, nofollow"
