backend:
  # For now, use the local proxy (no OAuth needed).
  # When you want remote editing later, switch to:
  #   name: git-gateway   (Netlify Identity)
  # or name: github       (GitHub OAuth)
  name: git-gateway
  branch: main

local_backend: true
publish_mode: editorial_workflow

media_folder: "public/assets/images/uploads"   # where files go in the repo
public_folder: "/assets/images/uploads"        # how they’re referenced in the site

collections:
  # -------- SINGLE-FILE EDITS (JSON in _data) --------
  - label: "Site Settings"
    name: "site_settings"
    files:
      - label: "General"
        name: "site"
        file: "_data/site.json"
        format: "json"
        fields:
          - { label: "Site Name", name: "name", widget: "string" }
          - { label: "Title (optional)", name: "title", widget: "string", required: false }
          - { label: "Site URL", name: "url", widget: "string" }
          - { label: "Description", name: "description", widget: "text" }
          - { label: "Phone", name: "phone", widget: "string" }
          - { label: "Email", name: "email", widget: "string" }
          - { label: "Logo Path", name: "logo", widget: "string", default: "/assets/images/COMPANY-LOGO.png" }
          - { label: "Google Tag Manager ID", name: "gtm_id", widget: "string", required: false }
          - { label: "Google Site Verification", name: "google_site_verification", widget: "string", required: false }
          - label: "Social Links"
            name: "social"
            widget: "list"
            fields:
              - { label: "Platform", name: "platform", widget: "select", options: [facebook, x, twitter, instagram, youtube] }
              - { label: "URL", name: "url", widget: "string" }

      - label: "SEO Defaults"
        name: "seo"
        file: "_data/seo.json"
        format: "json"
        fields:
          - { label: "Title Suffix", name: "titleSuffix", widget: "string", required: false }
          - { label: "Default Description", name: "defaultDescription", widget: "text", required: false }
          - { label: "OG Image (URL or path)", name: "ogImage", widget: "string", required: false }
          - { label: "OG Image Alt", name: "ogImageAlt", widget: "string", required: false }

      - label: "Navigation"
        name: "nav"
        file: "_data/nav.json"
        format: "json"
        fields:
          - label: "Main Nav"
            name: "main"
            widget: "list"
            fields:
              - { label: "Label", name: "label", widget: "string" }
              - { label: "URL", name: "url", widget: "string" }
          - label: "Footer Nav"
            name: "footer"
            widget: "list"
            fields:
              - { label: "Label", name: "label", widget: "string" }
              - { label: "URL", name: "url", widget: "string" }

  # -------- FOLDER COLLECTIONS --------
  - label: "Blog"
    name: "blog"
    folder: "content/blog"
    create: true
    slug: "{{slug}}"
    extension: "md"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Description", name: "description", widget: "text", required: false }
      - { label: "Draft", name: "draft", widget: "boolean", default: false }
      - { label: "Body", name: "body", widget: "markdown" }

  - label: "Services"
    name: "services"
    folder: "content/services"
    create: true
    slug: "{{slug}}"
    extension: "md"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text", required: false }
      - { label: "Draft", name: "draft", widget: "boolean", default: false }
      - { label: "Body", name: "body", widget: "markdown" }

  - label: "Locations"
    name: "locations"
    folder: "content/locations"
    create: true
    slug: "{{slug}}"
    extension: "md"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text", required: false }
      - { label: "Draft", name: "draft", widget: "boolean", default: false }
      - { label: "Body", name: "body", widget: "markdown" }
